version: '3'
services:
  drawio:
    image: jgraph/drawio:17.2.1
    container_name: drawio
    environment:
      VIRTUAL_PORT: 8080
      VIRTUAL_HOST: "foo.bar.com"
      LETSENCRYPT_HOST: "bar.com"
    networks:
      - nginx-proxy
    restart: always
    
networks:
  nginx-proxy:
    external: true
    name: "nginx-proxy"

