version: '3.4'

services:
  whoami:
    image: jwilder/whoami
    container_name: whoami
    expose:
      - "8000"
    environment:
      HTTPS_METHOD: nohttps
#      LETSENCRYPT_HOST: "${LETSENCRYPT_HOST:-bar.com}"
      VIRTUAL_PORT: "${VIRTUAL_PORT:-8000}"
      VIRTUAL_HOST: "${VIRTUAL_HOST:-foo.bar.com}"
      VIRTUAL_PATH: "${VIRTUAL_PAHT:-/whoami}"

    networks:
      - "nginx-proxy"
    restart: always
    
networks:
  nginx-proxy:
    external: true
    name: "nginx-proxy"

