version: '3.4'

services:
  drawio:
    image: jgraph/drawio:17.2.1
    container_name: drawio
    expose:
      - "8080"
    environment:
      HTTPS_METHOD: nohttps
#      LETSENCRYPT_HOST: "${LETSENCRYPT_HOST:-bar.com}"
      VIRTUAL_PORT: "${VIRTUAL_PORT:-8080}"
      VIRTUAL_HOST: "${VIRTUAL_HOST:-foo.bar.com}"
      VIRTUAL_PATH: "${VIRTUAL_PATH:-/}"
    networks:
      - "nginx-proxy"
    restart: always
    
networks:
  nginx-proxy:
    external: true
    name: "nginx-proxy"

