version: "3.4"

services:
  ifconfig:
    image: georgyo/ifconfig.io:latest
    container_name: ifconfig.io
    expose:
      - "8080"
    environment:
      HTTPS_METHOD: nohttps
#      LETSENCRYPT_HOST: "${LETSENCRYPT_HOST:-bar.com}"
      VIRTUAL_PORT: "${VIRTUAL_PORT:-8080}"
      VIRTUAL_HOST: "${VIRTUAL_HOST:-foo.bar.com}"
      VIRTUAL_PATH: "${VIRTUAL_PATH:-/}"
      TLS: ${TLS:-0}
      HOSTNAME: "${HOSTNAME}"
    networks:
      - "nginx-proxy"
    restart: always
    
networks:
  nginx-proxy:
    external: true
    name: "nginx-proxy"

